#!/bin/bash
create-vm: 
    ansible-playbook -i inventory.ini \
        playbooks/create-vm.yaml -b

destroy-vm: 
    ansible-playbook -i inventory.ini \
        playbooks/destroy-vm.yaml

create-masters: 
    ansible-playbook -i inventory.ini \
        playbooks/create-masters.yaml
create-workers: 
    ansible-playbook -i inventory.ini \
        playbooks/create-workers.yaml
ping-all: 
    ansible -i inventory.ini \
        all -m ping 