[all:vars]
ansible_user=kk
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# ansible_ssh_private_key_file=~/.ssh/
# ansible_ssh_private_key_file=~/.ssh/id_ed25519

[nfs-server]
localhost ansible_connection=local # use jenkins as a nfs server 


[nfs-client]
; should use internal ip instead of public one 
client1 ansible_host=10.170.0.3
client2 ansible_host=10.170.0.4
client3 ansible_host=10.148.0.13
client4 ansible_host=10.148.0.14

[all:children]
nfs-server
nfs-client
