deployment:
  replicas: 1
service:
  type: LoadBalancer
ports:
  web:
    port: 8000
    exposedPort: 80
  websecure:
    port: 8443
    exposedPort: 443
providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
api:
  dashboard: true
additionalArguments:
  - "--api.insecure=true"
  - "--api.dashboard=true"
  - "--certificatesresolvers.letsencrypt.acme.email=ponchannarith@gmail.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
persistence:
  enabled: true
  size: 128Mi
