- name: Setup NFS clients 
  hosts: nfs-client 
  become: true 
  tasks: 
  - name: Install common service 
    include_tasks: ../tasks/common-task.yaml
    when: false 
  - name: Setup NFS Client 
    include_tasks: ../tasks/nfs-client-task.yaml 