- name: Setup NFS server 
  hosts: nfs-server
  become: true 
  tasks:
    - name: Install Common Services 
      include_tasks: ../tasks/common-task.yaml
    - name: Setup NFS Server 
      include_tasks: ../tasks/nfs-server-task.yaml
   
   